import { Student } from '../types';

export type RosterStudent = Partial<Student> & {
  id: string;
  procNumber: string;
  name: string;
  email: string;
  avatar: string;
  grade: string;
  section: string;
  cycle: string;
  birthDate: string;
  gender: string;
  financialStatus: 'regular' | 'debito' | string;
  status: 'active' | 'inactive' | 'suspended';
  currentAverage: number;
  unexcusedAbsences: number;
  excusedAbsences: number;
  isTuitionPaidCurrentMonth: boolean;
};

export const CLASS_ROSTERS: Record<string, RosterStudent[]> = {
  'turma-10a': [
    {
      id: 'stu-afonso',
      procNumber: '2024-041',
      name: 'Afonso Miguel Santos Ramos',
      email: 'afonso.ramos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      grade: '10.ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '12/05/2009',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.8,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-1',
      procNumber: '2410',
      name: 'Tiago André Silva',
      email: 'tiago.silva@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '14/03/2008',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.4,
      unexcusedAbsences: 2,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-2',
      procNumber: '2404',
      name: 'Maria Francisca Gomes',
      email: 'maria.gomes@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '22/07/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 17.2,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-3',
      procNumber: '2389',
      name: 'Beatriz Santos Ramos',
      email: 'beatriz.ramos@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '11/09/2008',
      gender: 'Feminino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 15.0,
      unexcusedAbsences: 3,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-4',
      procNumber: '2415',
      name: 'Tomás Afonso Matos',
      email: 'tomas.matos@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '05/01/2008',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 14.8,
      unexcusedAbsences: 1,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-5',
      procNumber: '2422',
      name: 'Mariana Castro Ferreira',
      email: 'mariana.ferreira@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '19/04/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.0,
      unexcusedAbsences: 1,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-6',
      procNumber: '2398',
      name: 'Gonçalo Nuno Barreto',
      email: 'goncalo.barreto@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '30/11/2007',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 13.9,
      unexcusedAbsences: 4,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-7',
      procNumber: 'BM-2023-8702',
      name: 'Carlos Eduardo Henriques',
      email: 'carlos.henriques@bandmed.edu.pt',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      grade: '10º Ano',
      section: 'A',
      cycle: 'Ensino Secundário',
      birthDate: '15/02/2008',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 9.8,
      unexcusedAbsences: 11,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: false
    }
  ],

  'turma-10b': [
    {
      id: 'stu-10b-1',
      procNumber: '2431',
      name: 'Bernardo Kiala António',
      email: 'bernardo.antonio@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '10/02/2008',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 14.5,
      unexcusedAbsences: 1,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-10b-2',
      procNumber: '2432',
      name: 'Cecília Vanda Sebastião',
      email: 'cecilia.sebastiao@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '25/08/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.2,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-10b-3',
      procNumber: '2433',
      name: 'Daniel Mukeba Luvualu',
      email: 'daniel.luvualu@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '14/11/2008',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 11.0,
      unexcusedAbsences: 4,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-10b-4',
      procNumber: '2434',
      name: 'Esperança Pinto Chissola',
      email: 'esperanca.chissola@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '03/05/2009',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.1,
      unexcusedAbsences: 0,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-10b-5',
      procNumber: '2435',
      name: 'Fernando Caxito Domingos',
      email: 'fernando.domingos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '19/09/2008',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 13.8,
      unexcusedAbsences: 2,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-10b-6',
      procNumber: '2436',
      name: 'Graça Ndombele Manuel',
      email: 'graca.manuel@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '12/01/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 14.9,
      unexcusedAbsences: 1,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-10b-7',
      procNumber: '2437',
      name: 'Hélder Samahina Felix',
      email: 'helder.felix@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '27/06/2008',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 10.4,
      unexcusedAbsences: 5,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-10b-8',
      procNumber: '2438',
      name: 'Inês Quipungo Cafeca',
      email: 'ines.cafeca@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      grade: '10ª Classe',
      section: 'B',
      cycle: 'Ensino Secundário Geral',
      birthDate: '08/04/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.7,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    }
  ],

  'turma-11a': [
    {
      id: 'stu-11a-1',
      procNumber: '2351',
      name: 'Artur Cassoma Quaresma',
      email: 'artur.quaresma@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '18/03/2007',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.2,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11a-2',
      procNumber: '2352',
      name: 'Bruna Chissola de Carvalho',
      email: 'bruna.carvalho@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '09/07/2007',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.8,
      unexcusedAbsences: 1,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11a-3',
      procNumber: '2353',
      name: 'Cristiano Luvualu Bernardo',
      email: 'cristiano.bernardo@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '23/11/2007',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 12.1,
      unexcusedAbsences: 6,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-11a-4',
      procNumber: '2354',
      name: 'Dalila Mwene Domingos',
      email: 'dalila.domingos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '15/02/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 14.9,
      unexcusedAbsences: 1,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11a-5',
      procNumber: '2355',
      name: 'Edmilson Pedro Manuel',
      email: 'edmilson.manuel@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '04/09/2007',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 13.5,
      unexcusedAbsences: 2,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11a-6',
      procNumber: '2356',
      name: 'Flávia Gonga Henriques',
      email: 'flavia.henriques@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '17/04/2007',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 17.0,
      unexcusedAbsences: 0,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11a-7',
      procNumber: '2357',
      name: 'Helena Muachifi Gomes',
      email: 'helena.gomes@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '28/08/2007',
      gender: 'Feminino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 11.4,
      unexcusedAbsences: 5,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-11a-8',
      procNumber: '2358',
      name: 'Isaías Bumba Ferreira',
      email: 'isaias.ferreira@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      grade: '11ª Classe',
      section: 'A',
      cycle: 'Ensino Secundário Geral',
      birthDate: '11/01/2008',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.3,
      unexcusedAbsences: 1,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    }
  ],

  'turma-11b': [
    {
      id: 'stu-11b-1',
      procNumber: '2371',
      name: 'Joaquim Luvualu Mateus',
      email: 'joaquim.mateus@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      grade: '11ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '21/05/2007',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.6,
      unexcusedAbsences: 0,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11b-2',
      procNumber: '2372',
      name: 'Kieza Sambulungo Cafeca',
      email: 'kieza.cafeca@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      grade: '11ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '12/10/2007',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 14.8,
      unexcusedAbsences: 1,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11b-3',
      procNumber: '2373',
      name: 'Laurindo Felix Capusso',
      email: 'laurindo.capusso@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      grade: '11ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '07/03/2007',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 10.9,
      unexcusedAbsences: 8,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-11b-4',
      procNumber: '2374',
      name: 'Madalena Vissapa Sabino',
      email: 'madalena.sabino@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      grade: '11ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '16/09/2008',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.4,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11b-5',
      procNumber: '2375',
      name: 'Nelson Mukeba Santos',
      email: 'nelson.santos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      grade: '11ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '30/01/2007',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 13.7,
      unexcusedAbsences: 3,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-11b-6',
      procNumber: '2376',
      name: 'Quitéria Pinto Matos',
      email: 'quiteria.matos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      grade: '11ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '24/11/2007',
      gender: 'Feminino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 11.2,
      unexcusedAbsences: 4,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: false
    }
  ],

  'turma-12a': [
    {
      id: 'stu-12a-1',
      procNumber: '2281',
      name: 'Anabela K. Samahina',
      email: 'anabela.samahina@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      grade: '12ª Classe',
      section: 'A',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '04/02/2006',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 17.5,
      unexcusedAbsences: 0,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-12a-2',
      procNumber: '2282',
      name: 'Bruno Sambulungo Felix',
      email: 'bruno.felix@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      grade: '12ª Classe',
      section: 'A',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '19/06/2006',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.1,
      unexcusedAbsences: 1,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-12a-3',
      procNumber: '2283',
      name: 'Cláudia Cafeca Sabino',
      email: 'claudia.sabino@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      grade: '12ª Classe',
      section: 'A',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '11/12/2006',
      gender: 'Feminino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 12.3,
      unexcusedAbsences: 6,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-12a-4',
      procNumber: '2284',
      name: 'Diogo Vissapa Capusso',
      email: 'diogo.capusso@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      grade: '12ª Classe',
      section: 'A',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '29/08/2006',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.4,
      unexcusedAbsences: 1,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-12a-5',
      procNumber: '2285',
      name: 'Henrique de Carvalho Luvualu',
      email: 'henrique.luvualu@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      grade: '12ª Classe',
      section: 'A',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '15/03/2006',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 10.8,
      unexcusedAbsences: 7,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-12a-6',
      procNumber: '2286',
      name: 'Isabel Mwene Afonso',
      email: 'isabel.afonso@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      grade: '12ª Classe',
      section: 'A',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '22/10/2006',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 17.8,
      unexcusedAbsences: 0,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    }
  ],

  'turma-12b': [
    {
      id: 'stu-12b-1',
      procNumber: '2291',
      name: 'Braulio de Freitas Mendes',
      email: 'braulio.mendes@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      grade: '12ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '14/01/2006',
      gender: 'Masculino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.8,
      unexcusedAbsences: 0,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-12b-2',
      procNumber: '2292',
      name: 'Carla Ndala Gomes',
      email: 'carla.gomes@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      grade: '12ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '05/06/2006',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 15.9,
      unexcusedAbsences: 1,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-12b-3',
      procNumber: '2293',
      name: 'David Gusmão Ramos',
      email: 'david.ramos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      grade: '12ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '20/09/2006',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 11.5,
      unexcusedAbsences: 5,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-12b-4',
      procNumber: '2294',
      name: 'Eva Quarta Matos',
      email: 'eva.matos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      grade: '12ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '17/04/2006',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 14.7,
      unexcusedAbsences: 2,
      excusedAbsences: 1,
      isTuitionPaidCurrentMonth: true
    },
    {
      id: 'stu-12b-5',
      procNumber: '2295',
      name: 'Horácio Quaresma Santos',
      email: 'horacio.santos@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      grade: '12ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '08/11/2006',
      gender: 'Masculino',
      financialStatus: 'debito',
      status: 'active',
      currentAverage: 10.2,
      unexcusedAbsences: 9,
      excusedAbsences: 2,
      isTuitionPaidCurrentMonth: false
    },
    {
      id: 'stu-12b-6',
      procNumber: '2296',
      name: 'Ivone Chissola Pinto',
      email: 'ivone.pinto@bandmed.ao',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      grade: '12ª Classe',
      section: 'B',
      cycle: 'Ensino Médio / Secundário Geral',
      birthDate: '23/07/2006',
      gender: 'Feminino',
      financialStatus: 'regular',
      status: 'active',
      currentAverage: 16.5,
      unexcusedAbsences: 0,
      excusedAbsences: 0,
      isTuitionPaidCurrentMonth: true
    }
  ]
};

/**
 * Returns the list of enrolled students for a specific class.
 * First searches in db.students. If none found for that classId, loads from CLASS_ROSTERS.
 */
export function getStudentsForClass(classId: string, allDbStudents: Student[], className?: string): Student[] {
  const matched = (allDbStudents || []).filter((s) => String(s.classId) === String(classId));
  if (matched.length > 0) {
    return matched;
  }

  const defaultProps: Partial<Student> = {
    address: 'Luanda, Angola',
    nif: '005432198LA041',
    citizenCard: '005432198LA041',
    guardianName: 'Encarregado de Educação',
    guardianPhone: '+244 923 000 111',
    guardianEmail: 'encarregado@email.ao',
    guardianNif: '004123987LA022',
    attendanceRate: 98
  };

  const predefined = CLASS_ROSTERS[classId];
  if (predefined && predefined.length > 0) {
    return predefined.map((st) => ({
      ...defaultProps,
      ...st,
      classId,
      className: className || classId
    })) as Student[];
  }

  // Fallback: return any first 8 students mapped to this classId
  return (allDbStudents || []).slice(0, 8).map((st, idx) => ({
    ...defaultProps,
    ...st,
    id: `stu-${classId}-${idx + 1}`,
    classId,
    className: className || classId
  })) as Student[];
}
